[package]
name = "external"
version = "0.2.0"
edition = "2021"

[dependencies]
proconio = "0.5.0"
itertools = "0.14.0"
# num = "0.4"
num-integer = "0.1.46"
# num-bigint = "0.4"
superslice = "1.0.0"

ac-library-rs = "0.2.0"
rand = "0.9.2"
